# Generated by Django 5.1.6 on 2025-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NOME', max_length=125)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=11)),
                ('email', models.CharField(db_column='ENAIL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CONTATO',
            },
        ),
    ]
